services:
  db:
    image: postgres:15
    container_name: schedule_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schedule_db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/db_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - schedule-network

  backend:
    build: ./backend
    container_name: schedule_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: schedule_db
      DB_PORT: 5432
    networks:
      - schedule-network

  frontend:
    build: ./frontend
    container_name: schedule_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - schedule-network

networks:
  schedule-network:

volumes:
  db-data:
